language: php

php:
    - 7.2
    - 7.3
    - nightly

matrix:
    allow_failures:
        - php: nightly

services:
    - mysql

script:
    - php vendor/bin/phpunit -v

before_install:
    - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot;

before_script:
    - composer install --prefer-source
